services:
  main:
    restart: always
    # build: .
    image: honusan
    env_file:
      - .env
    volumes:
      # - ./.env:/app/.env:ro
      - ./index.js:/app/index.js
      - ./wbook.json:/app/wbook.json:rw
      - ./logs/:/app/logs
    command: node /app/index.js
    network_mode: host